# Generated by Django 2.2 on 2021-03-04 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(max_length=100, verbose_name='наименование отдела')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=100, verbose_name='наименование должности')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='where_work', to='application.Department')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.EmployeeRole')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.TextField(max_length=100, verbose_name='ФИО соискателя')),
                ('phone_number', models.TextField(max_length=11, verbose_name='телефон соискателя')),
                ('position', models.TextField(max_length=30, verbose_name='должность')),
                ('interview_date', models.DateTimeField(auto_now_add=True, verbose_name='дата выдачи тестового задания')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='время на выполнение задания')),
                ('name_hr', models.TextField(max_length=100, verbose_name='ФИО сотрудника, проводившего собеседование')),
                ('position_hr', models.TextField(max_length=100, verbose_name='должность сотрудника, проводившего собеседование')),
                ('date_of_get', models.DateTimeField(verbose_name='дата получения результата тестового задания')),
                ('head_of_department_name', models.TextField(max_length=100, verbose_name='ФИО руководителя подразделения, получившего результат тестового задания')),
                ('department', models.ForeignKey(max_length=30, on_delete='подразделение', to='application.Department')),
            ],
        ),
    ]
