# Generated by Django 2.2 on 2021-03-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(max_length=100, verbose_name='наименование отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=100, verbose_name='наименование должности')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.TextField(max_length=100, verbose_name='ФИО соискателя')),
                ('phone_number', models.TextField(max_length=11, verbose_name='Телефон соискателя')),
                ('position', models.TextField(max_length=30, verbose_name='Вакансия')),
                ('interview_date', models.DateField(help_text='Пожалуйста, используйте поддерживаемый формат: ДД-ММ-ГГГГ.', verbose_name='дата выдачи тестового задания')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение задания')),
                ('date_of_get', models.DateField(blank=True, help_text='Пожалуйста, используйте поддерживаемый формат: ДД-ММ-ГГГГ.', null=True, verbose_name='Дата получения результата тестового задания')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_department', to='application.Department', verbose_name='Наименование отдела')),
                ('department_hr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_department', to='application.Department', verbose_name='Название отдела, проводившего собеседование')),
            ],
        ),
    ]
