# Generated by Django 2.2 on 2021-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(max_length=100, verbose_name='наименование отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=100, verbose_name='наименование должности')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.TextField(max_length=100, verbose_name='ФИО соискателя')),
                ('phone_number', models.TextField(max_length=11, verbose_name='телефон соискателя')),
                ('position', models.TextField(max_length=30, verbose_name='должность')),
                ('interview_date', models.DateField(verbose_name='дата выдачи тестового задания')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='время на выполнение задания')),
                ('date_of_get', models.DateTimeField(blank=True, null=True, verbose_name='дата получения результата тестового задания')),
                ('head_of_department_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='ФИО руководителя подразделения, получившего результат тестового задания')),
                ('department', models.ForeignKey(on_delete='подразделение', related_name='applicant_department', to='application.Department')),
                ('department_hr', models.ForeignKey(on_delete='название отдела, проводившего собеседование', related_name='hr_department', to='application.Department')),
                ('name_hr', models.ForeignKey(max_length=100, on_delete='ФИО сотрудника, проводившего собеседование', to='application.Employee')),
                ('position_hr', models.ForeignKey(max_length=100, on_delete='должность сотрудника, проводившего собеседование', to='application.EmployeeRole')),
            ],
        ),
    ]
