# Generated by Django 2.2 on 2021-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_of_get',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата получения результата тестового задания'),
        ),
        migrations.AlterField(
            model_name='data',
            name='head_of_department_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='ФИО руководителя подразделения, получившего результат тестового задания'),
        ),
    ]
