# Generated by Django 2.2 on 2021-03-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='head_of_department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ФИО руководителя подразделения, получившего результат тестового задания'),
        ),
        migrations.AddField(
            model_name='record',
            name='name_hr',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='application.Employee', verbose_name='ФИО сотрудника, проводившего собеседование'),
        ),
        migrations.AddField(
            model_name='record',
            name='position_hr',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='application.EmployeeRole', verbose_name='Должность сотрудника, проводившего собеседование'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='application.Department', verbose_name='Наименование отдела'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='application.EmployeeRole', verbose_name='Должность сотрудника'),
        ),
    ]
