# Generated by Django 2.2 on 2021-03-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='where_work', to='application.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.EmployeeRole'),
        ),
    ]
