# Generated by Django 2.2 on 2021-03-07 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210306_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='application.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='application.EmployeeRole'),
        ),
    ]
