# Generated by Django 2.2 on 2021-03-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210304_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.TextField(max_length=100, verbose_name='ФИО соискателя')),
                ('phone_number', models.TextField(max_length=11, verbose_name='телефон соискателя')),
                ('position', models.TextField(max_length=30, verbose_name='должность')),
                ('interview_date', models.DateTimeField(verbose_name='дата выдачи тестового задания')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='время на выполнение задания')),
                ('name_hr', models.TextField(max_length=100, verbose_name='ФИО сотрудника, проводившего собеседование')),
                ('position_hr', models.TextField(max_length=100, verbose_name='должность сотрудника, проводившего собеседование')),
                ('date_of_get', models.DateTimeField(blank=True, null=True, verbose_name='дата получения результата тестового задания')),
                ('head_of_department_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='ФИО руководителя подразделения, получившего результат тестового задания')),
                ('department', models.ForeignKey(max_length=30, on_delete='подразделение', to='application.Department')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
