# Generated by Django 2.2 on 2021-03-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210305_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='interview_date',
            field=models.DateField(verbose_name='дата выдачи тестового задания'),
        ),
    ]
