# Generated by Django 2.2 on 2021-03-07 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210307_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='head_of_department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete='ФИО руководителя подразделения, получившего результат тестового задания', to=settings.AUTH_USER_MODEL),
        ),
    ]
